// Copyright (c) 2012-2019 Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#pragma once

#if defined(__cplusplus)
extern "C" {
#endif

typedef struct fontConfig_s fontConfig_t;
typedef struct fontConfigs_s fontConfigs_t;
typedef struct sb_s sb_t;
typedef struct sbs_s sbs_t;
typedef struct sdictEntry_s sdictEntry_t;
typedef struct sdict_s sdict_t;
typedef struct uuid_node_s uuid_node_t;

void fontConfig_reset(fontConfig_t *val);
void fontConfigs_reset(fontConfigs_t *val);
void sb_reset_from_loc(const char *file, int line, sb_t *val);
void sbs_reset_from_loc(const char *file, int line, sbs_t *val);
void sdictEntry_reset(sdictEntry_t *val);
void sdict_reset(sdict_t *val);
void uuid_node_reset(uuid_node_t *val);

fontConfig_t fontConfig_clone(const fontConfig_t *src);
fontConfigs_t fontConfigs_clone(const fontConfigs_t *src);
sb_t sb_clone_from_loc(const char *file, int line, const sb_t *src);
sbs_t sbs_clone_from_loc(const char *file, int line, const sbs_t *src);
sdictEntry_t sdictEntry_clone(const sdictEntry_t *src);
sdict_t sdict_clone(const sdict_t *src);
uuid_node_t uuid_node_clone(const uuid_node_t *src);

#if defined(__cplusplus)
} // extern "C"
#endif
